run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck

    - revive
    - gofmt
    - goimports
    - misspell
    - unconvert
    - goconst

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 3
  gofmt:
    simplify: true
